### ISSUE TITLE
Talk-to interactions repeat and interrupt in-progress dialogue

### ISSUE THREAD

**Issue by OzzyCallooh** [Explv/Tutorial-Island#13]
I have noticed that sometimes the bot repeats Talk-to interactions on NPCs despite already being in a dialogue with the NPC currently being talked-to. Generally, this happens with the Gelinor guide and Quest guide, but I've seen it happen with the chef and Vannaka.

This bug occurs more often when using lowcpu mode, or when the framerate is generally low. Will update this issue and/or make a PR if I can find a fix for this.

**Comment by phqnta** [comment]
This is an Osbot issue, client bugs out sometimes when your Cpu/ram usage is high.
