### ISSUE TITLE
Bots get stuck on lowcpu mode

### ISSUE THREAD

**Issue by NubeBuster** [Explv/Tutorial-Island#8]
Hey there, I would like to share a problem I have encountered several times.
The bots get stuck at the gate after the mining section when they dont successfully open it. The TutorialIsland.java selects the current section based on the progress bar, but that bar updates before they go through the gate.
The failure of opening the gate is probably caused by the fact that I run them on lowcpu 40 at a time 100% cpu load.

A potential fix would be to check if they are in the right area.

This problem occurs about 1/20 times for me

**Comment by NubeBuster** [comment]
Update:
I did not read the code, but I see this is caused differently;
If in the Fighting Section this code is changed:
`if (!getMap().canReach(getInstructor())) {
				RS2Object gate = getObjects().closest("Gate");
				if (gate != null)
					gate.interact("Open")
				sleep(4000);
			}`
to this
`if (!getMap().canReach(getInstructor())) {
				RS2Object gate = getObjects().closest("Gate");
				if (gate != null)
					if (!gate.interact("Open"))
						return;
				sleep(4000);
			}`

It would be fixed

**Comment by ghost** [comment]
I don't see why avoiding the sleep if the gate fails to open should fix it, have you tested this?

A more solid solution would be to check if the bot is still in the mining area, and if so try to interact with the gate again. And if we are not in the mining area anymore then just continue as usual.

**Comment by NubeBuster** [comment]
I have checked the code more, and they really shouldn't be getting stuck. I don't know how it happens. It's pretty common though

**Comment by NubeBuster** [comment]
I found the problem and made a pull request.
The problem was that the script tries to get into the rat area, but instead takes the wrong gate. Unlike the problem I thought it was
